pipeline {
    agent any
     tools {
        nodejs 'nodejs24.02'  // Use your configured Node.js version
    }
    stages {
        stage('Install') {
            steps {
                dir('app') { // or whatever folder contains package.json
                    bat 'npm install'
                }
            }
        }
        stage('Build') {
            steps {
                dir('app') {
                    bat 'npm run build'
                }
            }
        }
        stage('Deploy') {
            steps {
                 dir('app') {
                    bat 'xcopy /E /Y /I .next C:\\Websites\\BillingWeb\\azuredocker\\BillingApp\\app\\.next'
                    bat 'xcopy /E /Y /I public C:\\Websites\\BillingWeb\\azuredocker\\BillingApp\\app\\public'
                    bat 'xcopy /Y "next.config.ts" "C:\\Websites\\BillingWeb\\azuredocker\\BillingApp\\app\\"'
                    bat 'xcopy /E /Y /I out C:\\Websites\\BillingWeb\\azuredocker\\BillingApp\\app\\'
            }
            }
        }
    }
}
