pipeline {
    agent any
 
    stages {
        stage('CheckVersion') {
            steps {
                bat 'dotnet --version'
            }
        }
        stage('Restore') {
            steps {
                dir('api') {
                    bat 'dotnet restore api.csproj'
                }
            }
        }
        stage('Build') {
            steps {
                 dir('api') {
                    bat 'dotnet build --configuration Release'
                 }
              
            }
        }
        stage('Publish') {
            steps {
                 dir('api') {
                bat 'dotnet publish -c Release -o published'
                 }
            }
        }
        stage('Deploy') {
            steps {
                 dir('api') {
                bat 'xcopy /E /Y /I published C:\\Websites\\BillingWeb\\azuredocker\\BillingApp\\api'
                 }
            }
        }
    }
}
