pipeline {
    agent any
    tools {
        dotnet 'dotnet-9'
    }
    stages {
        stage('Restore') {
            steps {
                bat 'dotnet restore'
            }
        }
        stage('Build') {
            steps {
                bat 'dotnet build --configuration Release'
            }
        }
        stage('Publish') {
            steps {
                bat 'dotnet publish -c Release -o published'
            }
        }
        stage('Deploy') {
            steps {
                bat 'xcopy /E /Y /I published C:\\Websites\\BillingWeb\\azuredocker\\BillingApp\\api'
            }
        }
    }
}
